import Link from "next/link";
import { requireTenant } from "@/server/tenant";
import { db } from "@/server/db";
import { isMockAi } from "@/server/ai";
import { Card, StatusPill, PlatformBadge, btnStyles, SectionLabel, Pill } from "@/components/ui";
import { IdeaComposer } from "@/components/idea-composer";
import { lookPreviews } from "@/server/creative/looks";
import { GenerateStrategyButton } from "@/components/strategy-button";
import { formatDateTime, monthKey } from "@/lib/utils";

export const metadata = { title: "Home" };

function greeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 17) return "Good afternoon";
  return "Good evening";
}

export default async function DashboardPage({
  params,
}: {
  params: Promise<{ tenant: string }>;
}) {
  const { tenant: slug } = await params;
  const ctx = await requireTenant(slug);
  const tenantId = ctx.tenant.id;

  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);
  const todayEnd = new Date(todayStart);
  todayEnd.setDate(todayEnd.getDate() + 1);

  const [goal, todayItems, needsReview, recommendation, strategy, connectedCount] = await Promise.all([
    db.marketingGoal.findFirst({
      where: { tenantId, status: "ACTIVE", targetNumber: { not: null } },
      orderBy: { createdAt: "desc" },
    }),
    db.contentItem.findMany({
      where: {
        tenantId,
        scheduledAt: { gte: todayStart, lt: todayEnd },
        status: { notIn: ["ARCHIVED"] },
      },
      orderBy: { scheduledAt: "asc" },
      take: 6,
    }),
    db.contentItem.count({ where: { tenantId, status: "NEEDS_REVIEW" } }),
    db.aiInsight.findFirst({
      where: { tenantId, kind: "recommendation", status: "NEW" },
      orderBy: { createdAt: "desc" },
    }),
    db.marketingStrategy.findFirst({
      where: { tenantId, month: monthKey(), status: "ACTIVE" },
    }),
    db.socialAccount.count({ where: { tenantId, status: "CONNECTED" } }),
  ]);

  const picker = await lookPreviews(tenantId);

  const progress = goal?.targetNumber
    ? Math.min(100, Math.round((goal.currentNumber / goal.targetNumber) * 100))
    : 0;

  return (
    <main className="px-6 md:px-10 py-8 max-w-5xl">
      <header className="flex items-start justify-between gap-4 flex-wrap mb-6">
        <div>
          <h1 className="text-[26px] font-bold">
            {greeting()} <span aria-hidden="true">👋</span>
          </h1>
          <p className="text-ink-soft text-sm mt-1">{ctx.tenant.name}</p>
        </div>
        <Link href={`/app/${slug}/ideas/new`} className={btnStyles.idea}>
          + New Marketing Idea
        </Link>
      </header>

      {isMockAi() && (
        <div className="bg-saffron-tint text-saffron-deep text-sm rounded-[12px] px-4 py-3 mb-6">
          <b>Demo AI mode.</b> Marketing is generated by a local development stub, not a real model.
          Set <code>AI_PROVIDER=openai</code> and an API key to switch on real generation.
        </div>
      )}

      <div className="grid md:grid-cols-[1fr_1.5fr] gap-4 items-start">
        <Card>
          <SectionLabel>{goal ? `Monthly goal · ${goal.label.toLowerCase()}` : "Monthly goal"}</SectionLabel>
          {goal?.targetNumber ? (
            <>
              <div className="font-display text-[40px] font-extrabold leading-none tnum">
                {goal.currentNumber}
                <span className="text-lg text-ink-faint font-bold"> / {goal.targetNumber}</span>
              </div>
              <div className="h-2.5 rounded-full bg-surface-2 my-3.5 overflow-hidden">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-beet to-saffron"
                  style={{ width: `${progress}%` }}
                />
              </div>
              <p className="text-[12.5px] text-ink-soft">
                {connectedCount === 0
                  ? "Connect a platform to start tracking results against this goal."
                  : `${progress}% of the way there.`}
              </p>
            </>
          ) : (
            <p className="text-sm text-ink-soft">
              No number set yet.{" "}
              <Link href={`/app/${slug}/settings`} className="text-beet font-semibold">
                Set a monthly target
              </Link>{" "}
              so we can track progress.
            </p>
          )}
        </Card>

        <Card>
          <SectionLabel>Today&apos;s marketing</SectionLabel>
          {todayItems.length === 0 ? (
            <div className="py-2">
              <p className="text-sm text-ink-soft mb-3">
                {strategy
                  ? "Nothing scheduled for today."
                  : "No plan yet for this month. Let the AI build one from your goals."}
              </p>
              {!strategy && <GenerateStrategyButton slug={slug} />}
            </div>
          ) : (
            <ul>
              {todayItems.map((item, i) => (
                <li
                  key={item.id}
                  className={`flex items-center gap-3 py-3 ${i < todayItems.length - 1 ? "border-b border-line" : ""}`}
                >
                  <PlatformBadge platform={item.platform} size={30} />
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-sm truncate">{item.title}</div>
                    <div className="text-[12.5px] text-ink-soft">
                      {item.contentType.toLowerCase()} · {formatDateTime(item.scheduledAt)}
                    </div>
                  </div>
                  <StatusPill status={item.status} />
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>

      {needsReview > 0 && (
        <Card className="mt-4 flex items-center justify-between gap-4 flex-wrap">
          <div>
            <div className="font-bold">
              {needsReview} {needsReview === 1 ? "post is" : "posts are"} ready for your OK
            </div>
            <p className="text-sm text-ink-soft">Nothing goes out until you approve it.</p>
          </div>
          <Link href={`/app/${slug}/calendar?filter=review`} className={btnStyles.primary}>
            Review now
          </Link>
        </Card>
      )}

      {recommendation && (
        <div className="mt-4 rounded-[16px] p-5 border border-line bg-gradient-to-br from-beet-tint to-peacock-tint">
          <div className="text-[11.5px] font-extrabold uppercase tracking-[0.12em] text-beet-deep mb-1.5">
            AI recommendation
          </div>
          <div className="font-bold mb-1">{recommendation.title}</div>
          <p className="text-[14.5px] max-w-[58ch] mb-3">{recommendation.body}</p>
          <Link href={`/app/${slug}/analytics`} className={btnStyles.primary}>
            See the numbers
          </Link>
        </div>
      )}

      <section className="mt-8">
        <SectionLabel>Tell the AI what&apos;s happening</SectionLabel>
        <IdeaComposer slug={slug} {...picker} />
      </section>

      <section className="mt-8">
        <SectionLabel>Quick actions</SectionLabel>
        <div className="flex flex-wrap gap-2.5">
          <Link href={`/app/${slug}/products`} className={btnStyles.secondary}>+ Add product</Link>
          <Link href={`/app/${slug}/products`} className={btnStyles.secondary}>+ Add offer</Link>
          <Link href={`/app/${slug}/assets`} className={btnStyles.secondary}>Upload photo</Link>
          <Link href={`/app/${slug}/integrations`} className={btnStyles.secondary}>
            Connect platform
            {connectedCount === 0 && <Pill tone="saffron">none yet</Pill>}
          </Link>
        </div>
      </section>
    </main>
  );
}
